[package]
name = "monty"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.28.0", features = ["signal"] }
sha2 = "0.10.8"
structopt = "0.3.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indexmap = "1.9"
